### ISSUE TITLE
Only able to go to previous Warm-ups

### ISSUE THREAD

**Issue by Michionlion** [gkapfham/www.warmups.dev#9]
No "Next Warm-up" button is displayed on Warm-up 2 that links to Warm-up 3, although one is present on Warm-up 1 linking to Warm-up 2.

**Comment by gkapfham** [comment]
Hello @Michionlion thanks for raising this issue. I have correct the problem with the warmup buttons in the currently deployed version of the web site. Please note that I have not yet merged the content for the second and third warmups, but I hope to complete final implementation tasks for them and merge that material later today. Since I think that this issue is resolve, I am going to close it. If you notice that there is still a problem, please reopen the issue and comment accordingly.
